/**
 * Highway SIMD-optimized floor divide for signed and unsigned integer types.
 *
 * Uses NumPy's CPU dispatch system (NPY_CPU_DISPATCH_CURFX) to compile
 * multiple target variants (SVE, ASIMD, NEON for ARM; X86_V4/V3/V2 for x86).
 * Within each variant, Highway's HWY_STATIC_DISPATCH handles sub-target
 * selection at runtime (e.g. SVE vs SVE2, AVX2 vs AVX-512).
 *
 * Baseline (plain name, e.g. npy_highway_floor_divide_s8_contig) acts as a
 * trampoline: it uses NPY_CPU_DISPATCH_CALL_XB to dispatch to the best
 * available target-specific variant at runtime.
 *
 * Signed:   2x unrolled to hide load-to-use latency on ARM pipelines.
 * Unsigned: 4x unrolled (simpler path — no overflow/floor adjustment).
 */

#define _UMATHMODULE
#define _MULTIARRAYMODULE
#define NPY_NO_DEPRECATED_API NPY_API_VERSION

#include <limits>
#include <cstdint>

#include "numpy/ndarraytypes.h"
#include "numpy/npy_math.h"

// CPU dispatch macros: NPY_CPU_DISPATCH_CURFX, NPY_CPU_DISPATCH_CALL_XB, NPY_CPU_HAVE
#include "npy_cpu_dispatch.h"
// Per-source dispatch targets (SVE, etc.) — generated by mod_features.multi_targets()
#include "loops_arithmetic_floor_hwy.dispatch.h"

#include <hwy/highway.h>

#include "loops_arithmetic_floor_hwy.h"

HWY_BEFORE_NAMESPACE();

namespace HWY_NAMESPACE {

namespace hn = hwy::HWY_NAMESPACE;

template <typename T>
HWY_ATTR static void
simd_floor_divide(const T *HWY_RESTRICT src1, const T *HWY_RESTRICT src2,
                  T *HWY_RESTRICT dst, npy_intp len)
{
    constexpr T min_val = std::numeric_limits<T>::min();
    HWY_LANES_CONSTEXPR int vstep = static_cast<int>(hn::Lanes(hn::ScalableTag<T>()));

    const auto vneg_one = hn::Set(hn::ScalableTag<T>(), T(-1));
    const auto vzero = hn::Zero(hn::ScalableTag<T>());
    const auto vmin = hn::Set(hn::ScalableTag<T>(), min_val);
    const auto vone = hn::Set(hn::ScalableTag<T>(), T(1));

    bool warn_zero = false;
    bool warn_overflow = false;

    constexpr int unroll_factor = 2;
    const npy_intp vstep2 = vstep * unroll_factor;
    for (; len >= vstep2;
         len -= vstep2, src1 += vstep2, src2 += vstep2, dst += vstep2) {
        auto a0 = hn::LoadU(hn::ScalableTag<T>(), src1);
        auto b0 = hn::LoadU(hn::ScalableTag<T>(), src2);

        auto bzero0 = hn::Eq(b0, vzero);
        auto amin0 = hn::Eq(a0, vmin);
        auto bneg_one0 = hn::Eq(b0, vneg_one);
        auto overflow0 = hn::And(amin0, bneg_one0);

        if (!hn::AllFalse(hn::ScalableTag<T>(), bzero0)) {
            warn_zero = true;
        }
        if (!hn::AllFalse(hn::ScalableTag<T>(), overflow0)) {
            warn_overflow = true;
        }

        auto safe_b0 = hn::IfThenElse(hn::Or(bzero0, overflow0), vone, b0);
        auto quo0 = hn::Div(a0, safe_b0);

        auto rem0 = hn::Sub(a0, hn::Mul(quo0, safe_b0));
        auto a_pos0 = hn::Gt(a0, vzero);
        auto b_pos0 = hn::Gt(b0, vzero);
        auto same_sign0 = hn::Not(hn::Xor(a_pos0, b_pos0));
        auto rem_zero0 = hn::Eq(rem0, vzero);
        auto needs_adj0 = hn::And(hn::Not(same_sign0), hn::Not(rem_zero0));
        quo0 = hn::Add(quo0, hn::IfThenElse(needs_adj0, vneg_one, vzero));

        quo0 = hn::IfThenElse(bzero0, vzero, quo0);
        quo0 = hn::IfThenElse(overflow0, vmin, quo0);

        hn::StoreU(quo0, hn::ScalableTag<T>(), dst);

        auto a1 = hn::LoadU(hn::ScalableTag<T>(), src1 + vstep);
        auto b1 = hn::LoadU(hn::ScalableTag<T>(), src2 + vstep);

        auto bzero1 = hn::Eq(b1, vzero);
        auto amin1 = hn::Eq(a1, vmin);
        auto bneg_one1 = hn::Eq(b1, vneg_one);
        auto overflow1 = hn::And(amin1, bneg_one1);

        if (!hn::AllFalse(hn::ScalableTag<T>(), bzero1)) {
            warn_zero = true;
        }
        if (!hn::AllFalse(hn::ScalableTag<T>(), overflow1)) {
            warn_overflow = true;
        }

        auto safe_b1 = hn::IfThenElse(hn::Or(bzero1, overflow1), vone, b1);
        auto quo1 = hn::Div(a1, safe_b1);

        auto rem1 = hn::Sub(a1, hn::Mul(quo1, safe_b1));
        auto a_pos1 = hn::Gt(a1, vzero);
        auto b_pos1 = hn::Gt(b1, vzero);
        auto same_sign1 = hn::Not(hn::Xor(a_pos1, b_pos1));
        auto rem_zero1 = hn::Eq(rem1, vzero);
        auto needs_adj1 = hn::And(hn::Not(same_sign1), hn::Not(rem_zero1));
        quo1 = hn::Add(quo1, hn::IfThenElse(needs_adj1, vneg_one, vzero));

        quo1 = hn::IfThenElse(bzero1, vzero, quo1);
        quo1 = hn::IfThenElse(overflow1, vmin, quo1);

        hn::StoreU(quo1, hn::ScalableTag<T>(), dst + vstep);
    }

    for (; len >= vstep;
         len -= vstep, src1 += vstep, src2 += vstep, dst += vstep) {
        auto a = hn::LoadU(hn::ScalableTag<T>(), src1);
        auto b = hn::LoadU(hn::ScalableTag<T>(), src2);

        auto bzero = hn::Eq(b, vzero);
        auto amin = hn::Eq(a, vmin);
        auto bneg_one = hn::Eq(b, vneg_one);
        auto overflow = hn::And(amin, bneg_one);

        if (!hn::AllFalse(hn::ScalableTag<T>(), bzero)) {
            warn_zero = true;
        }
        if (!hn::AllFalse(hn::ScalableTag<T>(), overflow)) {
            warn_overflow = true;
        }

        auto safe_b = hn::IfThenElse(hn::Or(bzero, overflow), vone, b);
        auto quo = hn::Div(a, safe_b);

        auto rem = hn::Sub(a, hn::Mul(quo, safe_b));
        auto a_pos = hn::Gt(a, vzero);
        auto b_pos = hn::Gt(b, vzero);
        auto same_sign = hn::Not(hn::Xor(a_pos, b_pos));
        auto rem_zero = hn::Eq(rem, vzero);
        auto needs_adj = hn::And(hn::Not(same_sign), hn::Not(rem_zero));
        quo = hn::Add(quo, hn::IfThenElse(needs_adj, vneg_one, vzero));

        quo = hn::IfThenElse(bzero, vzero, quo);
        quo = hn::IfThenElse(overflow, vmin, quo);

        hn::StoreU(quo, hn::ScalableTag<T>(), dst);
    }

    if (warn_zero) {
        npy_set_floatstatus_divbyzero();
    }
    if (warn_overflow) {
        npy_set_floatstatus_overflow();
    }

    for (; len > 0; --len, ++src1, ++src2, ++dst) {
        const T a = *src1;
        const T b = *src2;
        if (NPY_UNLIKELY(b == 0)) {
            npy_set_floatstatus_divbyzero();
            *dst = 0;
        }
        else if (NPY_UNLIKELY(a == min_val && b == -1)) {
            npy_set_floatstatus_overflow();
            *dst = min_val;
        }
        else {
            T r = a / b;
            if (((a > 0) != (b > 0)) && ((r * b) != a)) {
                r--;
            }
            *dst = r;
        }
    }
}

template <typename T>
HWY_ATTR static void
simd_floor_divide_unsigned(const T *HWY_RESTRICT src1,
                           const T *HWY_RESTRICT src2,
                           T *HWY_RESTRICT dst, npy_intp len)
{
    HWY_LANES_CONSTEXPR int vstep = static_cast<int>(hn::Lanes(hn::ScalableTag<T>()));
    const auto vzero = hn::Zero(hn::ScalableTag<T>());
    const auto vone = hn::Set(hn::ScalableTag<T>(), T(1));
    bool warn_zero = false;

    const npy_intp vstep4 = vstep * 4;
    for (; len >= vstep4;
         len -= vstep4, src1 += vstep4, src2 += vstep4, dst += vstep4) {
        auto a0 = hn::LoadU(hn::ScalableTag<T>(), src1);
        auto b0 = hn::LoadU(hn::ScalableTag<T>(), src2);
        auto bz0 = hn::Eq(b0, vzero);
        if (!hn::AllFalse(hn::ScalableTag<T>(), bz0)) warn_zero = true;
        auto q0 = hn::Div(a0, hn::IfThenElse(bz0, vone, b0));
        q0 = hn::IfThenElse(bz0, vzero, q0);
        hn::StoreU(q0, hn::ScalableTag<T>(), dst);

        auto a1 = hn::LoadU(hn::ScalableTag<T>(), src1 + vstep);
        auto b1 = hn::LoadU(hn::ScalableTag<T>(), src2 + vstep);
        auto bz1 = hn::Eq(b1, vzero);
        if (!hn::AllFalse(hn::ScalableTag<T>(), bz1)) warn_zero = true;
        auto q1 = hn::Div(a1, hn::IfThenElse(bz1, vone, b1));
        q1 = hn::IfThenElse(bz1, vzero, q1);
        hn::StoreU(q1, hn::ScalableTag<T>(), dst + vstep);

        auto a2 = hn::LoadU(hn::ScalableTag<T>(), src1 + vstep * 2);
        auto b2 = hn::LoadU(hn::ScalableTag<T>(), src2 + vstep * 2);
        auto bz2 = hn::Eq(b2, vzero);
        if (!hn::AllFalse(hn::ScalableTag<T>(), bz2)) warn_zero = true;
        auto q2 = hn::Div(a2, hn::IfThenElse(bz2, vone, b2));
        q2 = hn::IfThenElse(bz2, vzero, q2);
        hn::StoreU(q2, hn::ScalableTag<T>(), dst + vstep * 2);

        auto a3 = hn::LoadU(hn::ScalableTag<T>(), src1 + vstep * 3);
        auto b3 = hn::LoadU(hn::ScalableTag<T>(), src2 + vstep * 3);
        auto bz3 = hn::Eq(b3, vzero);
        if (!hn::AllFalse(hn::ScalableTag<T>(), bz3)) warn_zero = true;
        auto q3 = hn::Div(a3, hn::IfThenElse(bz3, vone, b3));
        q3 = hn::IfThenElse(bz3, vzero, q3);
        hn::StoreU(q3, hn::ScalableTag<T>(), dst + vstep * 3);
    }

    const npy_intp vstep2 = vstep * 2;
    for (; len >= vstep2;
         len -= vstep2, src1 += vstep2, src2 += vstep2, dst += vstep2) {
        auto a0 = hn::LoadU(hn::ScalableTag<T>(), src1);
        auto b0 = hn::LoadU(hn::ScalableTag<T>(), src2);
        auto bz0 = hn::Eq(b0, vzero);
        if (!hn::AllFalse(hn::ScalableTag<T>(), bz0)) warn_zero = true;
        auto q0 = hn::Div(a0, hn::IfThenElse(bz0, vone, b0));
        q0 = hn::IfThenElse(bz0, vzero, q0);
        hn::StoreU(q0, hn::ScalableTag<T>(), dst);

        auto a1 = hn::LoadU(hn::ScalableTag<T>(), src1 + vstep);
        auto b1 = hn::LoadU(hn::ScalableTag<T>(), src2 + vstep);
        auto bz1 = hn::Eq(b1, vzero);
        if (!hn::AllFalse(hn::ScalableTag<T>(), bz1)) warn_zero = true;
        auto q1 = hn::Div(a1, hn::IfThenElse(bz1, vone, b1));
        q1 = hn::IfThenElse(bz1, vzero, q1);
        hn::StoreU(q1, hn::ScalableTag<T>(), dst + vstep);
    }

    for (; len >= vstep;
         len -= vstep, src1 += vstep, src2 += vstep, dst += vstep) {
        auto a = hn::LoadU(hn::ScalableTag<T>(), src1);
        auto b = hn::LoadU(hn::ScalableTag<T>(), src2);
        auto bz = hn::Eq(b, vzero);
        if (!hn::AllFalse(hn::ScalableTag<T>(), bz)) warn_zero = true;
        auto q = hn::Div(a, hn::IfThenElse(bz, vone, b));
        q = hn::IfThenElse(bz, vzero, q);
        hn::StoreU(q, hn::ScalableTag<T>(), dst);
    }

    if (warn_zero) {
        npy_set_floatstatus_divbyzero();
    }

    for (; len > 0; --len, ++src1, ++src2, ++dst) {
        const T a = *src1;
        const T b = *src2;
        if (NPY_UNLIKELY(b == 0)) {
            npy_set_floatstatus_divbyzero();
            *dst = 0;
        }
        else {
            *dst = a / b;
        }
    }
}

} // namespace HWY_NAMESPACE

HWY_AFTER_NAMESPACE();

extern "C" {

#ifdef NPY_MTARGETS_CURRENT
/*
 * Target-specific compilation (e.g. SVE).
 * NPY_CPU_DISPATCH_CURFX(func_name) produces e.g. func_name_SVE.
 * Uses HWY_STATIC_DISPATCH for Highway's own sub-target selection
 * (e.g. SVE vs SVE2).
 */
#define FLOOR_DIVIDE_DISPATCH(func_name, simd_func, scalar_type) \
NPY_VISIBILITY_HIDDEN void \
NPY_CPU_DISPATCH_CURFX(func_name)(char **args, npy_intp len) \
{ \
    HWY_STATIC_DISPATCH(simd_func)( \
        reinterpret_cast<const scalar_type *>(args[0]), \
        reinterpret_cast<const scalar_type *>(args[1]), \
        reinterpret_cast<scalar_type *>(args[2]), len); \
}
#else
/*
 * Baseline compilation: plain func_name is the caller-facing entry point.
 * Dispatches at runtime to the best available target (e.g. func_name_SVE)
 * via NPY_CPU_DISPATCH_CALL_XB. If no target is available, falls through
 * to HWY_STATIC_DISPATCH (typically NEON on ARM64).
 */
typedef void (*floor_divide_func)(char **args, npy_intp len);

/* Forward-declare target-specific variants so NPY_CPU_DISPATCH_CALL_XB can
 * reference them. Each expands to e.g. void func_name_SVE(char**, npy_intp);
 * when the SVE target is enabled in the dispatch config. */
// NPY_CPU_DISPATCH_DECLARE_XB(void npy_highway_floor_divide_s8_contig,
//                             (char **args, npy_intp len));
NPY_CPU_DISPATCH_DECLARE_XB(void npy_highway_floor_divide_s16_contig,
                            (char **args, npy_intp len));
NPY_CPU_DISPATCH_DECLARE_XB(void npy_highway_floor_divide_s32_contig,
                            (char **args, npy_intp len));
// NPY_CPU_DISPATCH_DECLARE_XB(void npy_highway_floor_divide_u8_contig,
//                             (char **args, npy_intp len));
NPY_CPU_DISPATCH_DECLARE_XB(void npy_highway_floor_divide_u16_contig,
                            (char **args, npy_intp len));
NPY_CPU_DISPATCH_DECLARE_XB(void npy_highway_floor_divide_u32_contig,
                            (char **args, npy_intp len));

/* Dispatch macro for 8-bit: bypass NPY dispatch, use HWY_STATIC_DISPATCH                                                                
 * directly. On ARM64 (no SVE flags in baseline) this selects NEON/ASIMD. */                                                             
#define FLOOR_DIVIDE_DISPATCH_8BIT(func_name, simd_func, scalar_type) \                                                                  
NPY_VISIBILITY_HIDDEN void \                                                                                                             
NPY_CPU_DISPATCH_CURFX(func_name)(char **args, npy_intp len) \                                                                           
{ \                                                                                                                                      
    HWY_STATIC_DISPATCH(simd_func)( \                                                                                                    
        reinterpret_cast<const scalar_type *>(args[0]), \                                                                                
        reinterpret_cast<const scalar_type *>(args[1]), \                                                                                
        reinterpret_cast<scalar_type *>(args[2]), len); \                                                                                
} 

#define FLOOR_DIVIDE_DISPATCH(func_name, simd_func, scalar_type) \
NPY_VISIBILITY_HIDDEN void \
NPY_CPU_DISPATCH_CURFX(func_name)(char **args, npy_intp len) \
{ \
    floor_divide_func _f = NULL; \
    NPY_CPU_DISPATCH_CALL_XB(_f = func_name); \
    if (_f != NULL) { \
        _f(args, len); \
        return; \
    } \
    HWY_STATIC_DISPATCH(simd_func)( \
        reinterpret_cast<const scalar_type *>(args[0]), \
        reinterpret_cast<const scalar_type *>(args[1]), \
        reinterpret_cast<scalar_type *>(args[2]), len); \
}
#endif

/* Signed integer wrappers */
/* 8-bit: baseline-only, bypasses SVE (too slow for narrow 8-bit types). 
 * On ARM64, HWY_STATIC_DISPATCH in the baseline selects NEON/ASIMD. */ 
#ifndef NPY_MTARGETS_CURRENT  
FLOOR_DIVIDE_DISPATCH_8BIT(npy_highway_floor_divide_s8_contig,                                                                           
                           simd_floor_divide<int8_t>, int8_t)
#endif
FLOOR_DIVIDE_DISPATCH(npy_highway_floor_divide_s16_contig,
                      simd_floor_divide<int16_t>, int16_t)
FLOOR_DIVIDE_DISPATCH(npy_highway_floor_divide_s32_contig,
                      simd_floor_divide<int32_t>, int32_t)

/* Unsigned integer wrappers */

/* 8-bit unsigned: baseline-only, bypasses SVE (too slow for narrow types). */
#ifndef NPY_MTARGETS_CURRENT        
FLOOR_DIVIDE_DISPATCH_8BIT(npy_highway_floor_divide_u8_contig,                                                                           
                           simd_floor_divide_unsigned<uint8_t>, uint8_t) 
#endif

FLOOR_DIVIDE_DISPATCH(npy_highway_floor_divide_u16_contig,
                      simd_floor_divide_unsigned<uint16_t>, uint16_t)
FLOOR_DIVIDE_DISPATCH(npy_highway_floor_divide_u32_contig,
                      simd_floor_divide_unsigned<uint32_t>, uint32_t)

#undef FLOOR_DIVIDE_DISPATCH

}