/*
 * Copyright (c) 2025, NumPy Developers
 * Distributed under the BSD-3-Clause license
 * See LICENSE.txt for more information
 *
 * Highway SIMD-optimized complex maximum/minimum ufunc loop declarations.
 *
 * Provides extern "C" entry points for CFLOAT/CDOUBLE/CLONGDOUBLE maximum
 * and minimum ufunc loops.  The implementations live in
 * loops_complex_maxmin.dispatch.cpp and use Highway SIMD for float and
 * double types with a scalar fallback for long double.
 *
 * These replace the templated scalar complex max/min loops previously
 * generated by loops.c.src.
 */

#ifndef _NPY_UMATH_LOOPS_COMPLEX_MAXMIN_H_
#define _NPY_UMATH_LOOPS_COMPLEX_MAXMIN_H_

#include <numpy/npy_common.h>
#include <numpy/ndarraytypes.h>

#ifdef __cplusplus
extern "C" {
#endif

NPY_NO_EXPORT void
CFLOAT_maximum(char **args, npy_intp const *dimensions,
        npy_intp const *steps, void *NPY_UNUSED(func));

NPY_NO_EXPORT void
CFLOAT_minimum(char **args, npy_intp const *dimensions,
        npy_intp const *steps, void *NPY_UNUSED(func));

NPY_NO_EXPORT void
CDOUBLE_maximum(char **args, npy_intp const *dimensions,
        npy_intp const *steps, void *NPY_UNUSED(func));

NPY_NO_EXPORT void
CDOUBLE_minimum(char **args, npy_intp const *dimensions,
        npy_intp const *steps, void *NPY_UNUSED(func));

NPY_NO_EXPORT void
CLONGDOUBLE_maximum(char **args, npy_intp const *dimensions,
        npy_intp const *steps, void *NPY_UNUSED(func));

NPY_NO_EXPORT void
CLONGDOUBLE_minimum(char **args, npy_intp const *dimensions,
        npy_intp const *steps, void *NPY_UNUSED(func));

#ifdef __cplusplus
}
#endif

#endif /* _NPY_UMATH_LOOPS_COMPLEX_MAXMIN_H_ */
