/**
 * Highway SIMD-optimized pairwise summation for float/double and complex.
 *
 * Uses NumPy's CPU dispatch system (NPY_CPU_DISPATCH_CURFX) to compile
 * multiple target variants (SVE, ASIMD, NEON for ARM; X86_V4/V3/V2 for x86).
 * Within each variant, Highway's HWY_STATIC_DISPATCH handles sub-target
 * selection at runtime (e.g. SVE vs SVE2, AVX2 vs AVX-512).
 *
 * Baseline (plain name, e.g. npy_highway_pairwise_sum_f32_contig) acts as a
 * trampoline: it uses HWY_STATIC_DISPATCH directly since pairwise sum
 * benefits all SIMD targets including baseline NEON/AVX.
 *
 * Algorithm:
 * - Small arrays (n < 4*lanes): scalar loop with -0.0 init for correct signs
 * - Medium arrays (n <= 256): 4-way SIMD unroll with independent accumulators
 * - Large arrays: pairwise recursion aligned to unroll_len for SIMD efficiency
 */

#define _UMATHMODULE
#define _MULTIARRAYMODULE
#define NPY_NO_DEPRECATED_API NPY_API_VERSION

#include "numpy/ndarraytypes.h"
#include "numpy/npy_math.h"

/* CPU dispatch macros: NPY_CPU_DISPATCH_CURFX */
#include "npy_cpu_dispatch.h"
/* Per-source dispatch targets (SVE, etc.) - generated by mod_features */
#include "loops_arithm_sum_hwy.dispatch.h"

#include <hwy/highway.h>

#include "loops_arithm_sum_hwy.h"

HWY_BEFORE_NAMESPACE();

namespace HWY_NAMESPACE {

namespace hn = hwy::HWY_NAMESPACE;

/*
 * Pairwise sum for contiguous float/double arrays.
 * Uses 4 independent SIMD accumulators to break dependency chains,
 * improving instruction-level parallelism on modern CPUs.
 */
template <typename T>
HWY_ATTR static T
simd_pairwise_sum_contig(const T *HWY_RESTRICT a, npy_intp n)
{
    const hn::ScalableTag<T> d;
    HWY_LANES_CONSTEXPR npy_intp lanes = static_cast<npy_intp>(
        hn::Lanes(d));
    const npy_intp unroll_len = 4 * lanes;

    /* PW_BLOCKSIZE equivalent for Highway - larger for better SIMD usage */
    constexpr npy_intp hwy_blocksize = 256;

    /* Small case: insufficient elements for SIMD unroll */
    if (n < unroll_len) {
        T res = static_cast<T>(-0.0);
        for (npy_intp i = 0; i < n; i++) {
            res += a[i];
        }
        return res;
    }

    /* Medium case: single block with 4-way SIMD accumulator unroll */
    if (n <= hwy_blocksize) {
        auto acc0 = hn::Set(d, static_cast<T>(-0.0));
        auto acc1 = hn::Set(d, static_cast<T>(-0.0));
        auto acc2 = hn::Set(d, static_cast<T>(-0.0));
        auto acc3 = hn::Set(d, static_cast<T>(-0.0));

        npy_intp i = 0;

        /* Process 4 vectors per iteration to hide load-to-use latency */
        for (; i + unroll_len - 1 < n; i += unroll_len) {
            auto v0 = hn::LoadU(d, a + i);
            auto v1 = hn::LoadU(d, a + i + lanes);
            auto v2 = hn::LoadU(d, a + i + 2 * lanes);
            auto v3 = hn::LoadU(d, a + i + 3 * lanes);

            acc0 = hn::Add(acc0, v0);
            acc1 = hn::Add(acc1, v1);
            acc2 = hn::Add(acc2, v2);
            acc3 = hn::Add(acc3, v3);
        }

        /* Merge the 4 independent accumulators */
        acc0 = hn::Add(acc0, acc1);
        acc2 = hn::Add(acc2, acc3);
        acc0 = hn::Add(acc0, acc2);

        /* Horizontal reduction: sum all lanes to scalar */
        T sum = hn::ReduceSum(d, acc0);

        /* Handle remaining tail elements */
        for (; i < n; i++) {
            sum += a[i];
        }

        return sum;
    }

    /* Large case: pairwise recursion for numerical stability */
    npy_intp n2 = n / 2;

    /* Align split point to unroll_len for SIMD efficiency
     * Highway lane counts are powers of 2, so unroll_len is also power of 2 */
    n2 &= ~(unroll_len - 1);
    if (n2 == 0) {
        n2 = unroll_len;
    }

    return simd_pairwise_sum_contig<T>(a, n2) +
           simd_pairwise_sum_contig<T>(a + n2, n - n2);
}

/*
 * Pairwise sum for contiguous complex arrays.
 * Uses LoadInterleaved2 to efficiently de-interleave real and imaginary
 * parts from the interleaved storage format (R, I, R, I, ...).
 */
template <typename T>
HWY_ATTR static void
simd_complex_pairwise_sum_contig(T *HWY_RESTRICT rr, T *HWY_RESTRICT ri,
                                  const T *HWY_RESTRICT a, npy_intp n)
{
    const hn::ScalableTag<T> d;
    HWY_LANES_CONSTEXPR npy_intp lanes = static_cast<npy_intp>(
        hn::Lanes(d));
    const npy_intp unroll_len = 4 * lanes;

    /* n is total floating-point elements; nc is number of complex numbers */
    npy_intp nc = n / 2;

    /* Complex blocksize - half of real since we process real+imag together */
    constexpr npy_intp hwy_blocksize_c = 128;

    /* Small case: scalar loop */
    if (nc < unroll_len) {
        T res_r = static_cast<T>(-0.0);
        T res_i = static_cast<T>(-0.0);
        for (npy_intp i = 0; i < nc; i++) {
            res_r += a[2 * i];
            res_i += a[2 * i + 1];
        }
        *rr = res_r;
        *ri = res_i;
        return;
    }

    /* Medium case: 4-way SIMD unroll with separate real/imag accumulators */
    if (nc <= hwy_blocksize_c) {
        /* 4 independent real part accumulators */
        auto acc_r0 = hn::Set(d, static_cast<T>(-0.0));
        auto acc_r1 = hn::Set(d, static_cast<T>(-0.0));
        auto acc_r2 = hn::Set(d, static_cast<T>(-0.0));
        auto acc_r3 = hn::Set(d, static_cast<T>(-0.0));

        /* 4 independent imaginary part accumulators */
        auto acc_i0 = hn::Set(d, static_cast<T>(-0.0));
        auto acc_i1 = hn::Set(d, static_cast<T>(-0.0));
        auto acc_i2 = hn::Set(d, static_cast<T>(-0.0));
        auto acc_i3 = hn::Set(d, static_cast<T>(-0.0));

        npy_intp i = 0;

        /* Process 4 complex vectors per iteration */
        for (; i + unroll_len - 1 < nc; i += unroll_len) {
            hn::Vec<decltype(d)> vr0, vi0, vr1, vi1, vr2, vi2, vr3, vi3;

            /* LoadInterleaved2 de-interleaves (R,I,R,I,...) into
             * separate vectors for real (vr) and imaginary (vi) parts */
            hn::LoadInterleaved2(d, a + 2 * i, vr0, vi0);
            hn::LoadInterleaved2(d, a + 2 * (i + lanes), vr1, vi1);
            hn::LoadInterleaved2(d, a + 2 * (i + 2 * lanes), vr2, vi2);
            hn::LoadInterleaved2(d, a + 2 * (i + 3 * lanes), vr3, vi3);

            acc_r0 = hn::Add(acc_r0, vr0);
            acc_i0 = hn::Add(acc_i0, vi0);

            acc_r1 = hn::Add(acc_r1, vr1);
            acc_i1 = hn::Add(acc_i1, vi1);

            acc_r2 = hn::Add(acc_r2, vr2);
            acc_i2 = hn::Add(acc_i2, vi2);

            acc_r3 = hn::Add(acc_r3, vr3);
            acc_i3 = hn::Add(acc_i3, vi3);
        }

        /* Merge real part accumulators */
        acc_r0 = hn::Add(acc_r0, acc_r1);
        acc_r2 = hn::Add(acc_r2, acc_r3);
        acc_r0 = hn::Add(acc_r0, acc_r2);

        /* Merge imaginary part accumulators */
        acc_i0 = hn::Add(acc_i0, acc_i1);
        acc_i2 = hn::Add(acc_i2, acc_i3);
        acc_i0 = hn::Add(acc_i0, acc_i2);

        /* Horizontal reduction to scalar */
        T sum_r = hn::ReduceSum(d, acc_r0);
        T sum_i = hn::ReduceSum(d, acc_i0);

        /* Handle remaining tail complex elements */
        for (; i < nc; i++) {
            sum_r += a[2 * i];
            sum_i += a[2 * i + 1];
        }

        *rr = sum_r;
        *ri = sum_i;
        return;
    }

    /* Large case: pairwise recursion */
    npy_intp nc2 = nc / 2;

    /* Align split point to unroll_len */
    nc2 &= ~(unroll_len - 1);
    if (nc2 == 0) {
        nc2 = unroll_len;
    }

    T rr1, ri1, rr2, ri2;
    simd_complex_pairwise_sum_contig<T>(&rr1, &ri1, a, nc2 * 2);
    simd_complex_pairwise_sum_contig<T>(&rr2, &ri2, a + nc2 * 2,
                                        (nc - nc2) * 2);

    *rr = rr1 + rr2;
    *ri = ri1 + ri2;
}

}  /* namespace HWY_NAMESPACE */

HWY_AFTER_NAMESPACE();

extern "C" {

#ifdef NPY_MTARGETS_CURRENT
/*
 * Target-specific compilation (e.g. SVE, AVX2).
 * NPY_CPU_DISPATCH_CURFX(func_name) produces e.g. func_name_SVE.
 * Uses HWY_STATIC_DISPATCH for Highway's sub-target selection.
 */
#define SUM_DISPATCH(func_name, simd_func, type) \
NPY_VISIBILITY_HIDDEN type \
NPY_CPU_DISPATCH_CURFX(func_name)(const type *a, npy_intp n) \
{ \
    return HWY_STATIC_DISPATCH(simd_func)( \
        reinterpret_cast<const type *>(a), n); \
}

#define COMPLEX_SUM_DISPATCH(func_name, simd_func, type) \
NPY_VISIBILITY_HIDDEN void \
NPY_CPU_DISPATCH_CURFX(func_name)(type *rr, type *ri, \
                                   const type *a, npy_intp n) \
{ \
    HWY_STATIC_DISPATCH(simd_func)(rr, ri, \
        reinterpret_cast<const type *>(a), n); \
}

#else
/*
 * Baseline compilation: plain func_name is the caller-facing entry point.
 * Uses HWY_STATIC_DISPATCH directly since all SIMD targets benefit.
 * Highway automatically selects best available instruction set
 * (e.g. NEON on baseline ARM64, SSE2/AVX on baseline x86).
 */
#define SUM_DISPATCH(func_name, simd_func, type) \
NPY_VISIBILITY_HIDDEN type \
NPY_CPU_DISPATCH_CURFX(func_name)(const type *a, npy_intp n) \
{ \
    return HWY_STATIC_DISPATCH(simd_func)( \
        reinterpret_cast<const type *>(a), n); \
}

#define COMPLEX_SUM_DISPATCH(func_name, simd_func, type) \
NPY_VISIBILITY_HIDDEN void \
NPY_CPU_DISPATCH_CURFX(func_name)(type *rr, type *ri, \
                                   const type *a, npy_intp n) \
{ \
    HWY_STATIC_DISPATCH(simd_func)(rr, ri, \
        reinterpret_cast<const type *>(a), n); \
}

#endif

/* Real floating-point sum dispatch functions */
SUM_DISPATCH(npy_highway_pairwise_sum_f32_contig,
             simd_pairwise_sum_contig, float)
SUM_DISPATCH(npy_highway_pairwise_sum_f64_contig,
             simd_pairwise_sum_contig, double)

/* Complex floating-point sum dispatch functions */
COMPLEX_SUM_DISPATCH(npy_highway_complex_pairwise_sum_f32_contig,
                     simd_complex_pairwise_sum_contig, float)
COMPLEX_SUM_DISPATCH(npy_highway_complex_pairwise_sum_f64_contig,
                     simd_complex_pairwise_sum_contig, double)

#undef SUM_DISPATCH
#undef COMPLEX_SUM_DISPATCH

}  /* extern "C" */